//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Day6.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tmcezlum\r\nafzwmyrz\r\nollxkaqs\r\noqvdutkr\r\nufzmsidi\r\nwnidhqow\r\nefgwivmh\r\nendrsvkk\r\nn" +
            "raaoczx\r\nyghmfumn\r\nfcwrdzyt\r\nqbbejygt\r\nohrzbtul\r\nlmrarckg\r\nfrzhozsk\r\nahvqozmk\r\nc" +
            "noxuqjm\r\nnjudcxbx\r\nxjeohiim\r\nsygfjxcx\r\nfbmchcaa\r\nqqggrcwq\r\nvbcgurox\r\neujzkdmh\r\nk" +
            "bpinltk\r\nposxqzam\r\nrojnpogl\r\nzvhruwqw\r\nhvbrxcky\r\niqifiukd\r\nxetwaptt\r\nqvksnzoe\r\nn" +
            "ulslfja\r\ntphqwfte\r\nddencvfp\r\nnhabbwcl\r\njefzkclw\r\ntxstxeio\r\nyaaqxpdp\r\nefewzeqa\r\nt" +
            "eapznjk\r\njylnjhnf\r\njumelmrz\r\nziarkfwo\r\nvklsvaca\r\nuoyzpkbn\r\noovggzkn\r\najvmcuon\r\ng" +
            "kztjkss\r\nqnwohfwg\r\nkxwtvaez\r\njwavozvo\r\nqgqbbaoc\r\nxzdepoxu\r\nkbxhekyv\r\nceuqobnx\r\nq" +
            "lrejrjz\r\nfvknhyqb\r\ntfwsmaei\r\nofpzikkg\r\nxggckiou\r\navcoljdv\r\nvhzjtrwv\r\ndyqnywkg\r\nu" +
            "dobaedh\r\ngncyxisz\r\noedldehj\r\nssmyewfv\r\nciaphyxw\r\nfhizpimr\r\nbjyeqyzh\r\nowjojbzf\r\ns" +
            "kdfqaeq\r\nubspxbix\r\ntruvdgua\r\nttvftscb\r\nqjyxodqz\r\ncakskune\r\nokojmtim\r\nrvrhaprz\r\ni" +
            "ezxilxh\r\nyalqlefr\r\nrxygadto\r\nhdszdagc\r\nsrqhzltw\r\nvuinwxvi\r\njcunlnmn\r\njxolxqid\r\nm" +
            "nnjrghb\r\njogafqpd\r\nixdlwxwj\r\nsttkgdyk\r\niqfeawey\r\nzdlukwnn\r\nodghxddl\r\neoflpjdw\r\nh" +
            "aketaof\r\nylkfukna\r\npdwemhut\r\nryyhsryr\r\niapyhpba\r\nwtgsqrtt\r\nhctctzdi\r\nulnuyuex\r\nb" +
            "pxpdeqb\r\nitbourhl\r\ndztqwptk\r\ngmmsltml\r\nevnhvtiy\r\nasjexlfo\r\nsgxejmmg\r\nqxbhjpmp\r\np" +
            "rauglcy\r\nbulipmjg\r\nxjrkceql\r\nutehzgxa\r\nltvfsdrj\r\nlnyazzkp\r\nddnndirm\r\nbddvibpq\r\na" +
            "jxjxdls\r\nuidqyood\r\ncjqffbdm\r\nnzonwmsr\r\nzmcesyao\r\nwvfwtwuc\r\npwuqzzvg\r\neciaebxq\r\nv" +
            "xbuvava\r\nyhalnneq\r\npejiyegy\r\ntsopxjfn\r\nggzatxrg\r\nlgnpyiko\r\neinylipk\r\ncwtgfpza\r\nn" +
            "iddiicg\r\nctqbwhzb\r\nmzpgsons\r\naqaxajai\r\nfkwufqgn\r\ndglewfob\r\nxoqdxsnr\r\nblxnybat\r\nb" +
            "ohqqthr\r\nqanfhczt\r\ngkpxjfrb\r\nzmewqucy\r\natuodurb\r\nsuiitdqe\r\nusywjzqc\r\nvoltqnvd\r\np" +
            "pstzuzb\r\nncxkbwul\r\nhgivkyyq\r\nbldyxpov\r\nyvjbraai\r\nfhqawceq\r\nnrmjvhnh\r\nkpwxogac\r\nt" +
            "rtzfnkp\r\npczcsgns\r\nrfjdromo\r\nuncmnnjj\r\neordqsju\r\nrhvpcncs\r\nhrokpyig\r\nbkszmpef\r\nk" +
            "rugmwkb\r\nsyvtsdek\r\nvigizldv\r\nvldwtfmv\r\nckcbqkrf\r\ndtvjipcw\r\nampjmdpd\r\nkcirijwv\r\nz" +
            "zufovbr\r\nolexgnqh\r\nllxddfsh\r\nwfnnkivb\r\ndzvcoxpi\r\nwpcwuqoc\r\nnejgfqvm\r\nmgbjcbst\r\nu" +
            "glwuejg\r\nrwfcpnpp\r\ndbfycvwm\r\nhisynlnw\r\ngglqswni\r\nwpmiixuf\r\nrqbfxlef\r\nlsupxzeu\r\nu" +
            "qrzsowl\r\nxqmgmnyk\r\ngzdfdbtb\r\naoyujvtz\r\nzmhsbsde\r\nxnmsgyvk\r\ngszwzotk\r\nfkbphiti\r\nl" +
            "ffmpdda\r\nplotuwbi\r\nhakfuxeb\r\ncpqzjdjb\r\nfoqwhfis\r\nctevnjly\r\nbbnuoohx\r\nzjndqgbv\r\nf" +
            "tmrakmg\r\nyphljbse\r\nvcmmtout\r\nishcbwpn\r\noysaacfd\r\nupawmrwj\r\ncexlaadr\r\ncezsoibf\r\ny" +
            "ydnylal\r\nmieypczr\r\nltbuvmfu\r\nekumekic\r\nkrbiejuo\r\ncyweeeht\r\nlugkftlh\r\npohkdvai\r\nx" +
            "goxbacm\r\ningicfit\r\ndclavjqp\r\ndnzgfbrc\r\njssnhcfu\r\ntxykgvhl\r\nuwvgyzgz\r\njecfzcoi\r\ny" +
            "aktumqx\r\noqehhika\r\nvoqmtwam\r\nwchhskdh\r\nkxjzeygs\r\nkrfjungf\r\niqamjkgh\r\najaxlbcr\r\nm" +
            "frdjjwz\r\njvqfkkjt\r\nmupueoje\r\nozvctxzd\r\nqneodvvw\r\nzisckhyc\r\nyxgudchh\r\noapmbpbc\r\np" +
            "yizuqnn\r\nttnblbho\r\nxdpiahgx\r\nlyerpyzv\r\ndzslbegp\r\nfvujdszc\r\nqhuhvkej\r\nwxktwmez\r\ni" +
            "rrqradv\r\nxtbqoxyg\r\nnhlrfrgy\r\ngocvpvlp\r\nbwybesby\r\nrvewprlo\r\nelwmmcos\r\nfertmhyj\r\nq" +
            "hxooqtq\r\ngzdaipgn\r\nyqfmniyt\r\ngornoejg\r\nwqgsxzys\r\nkxqaletd\r\nikuvaeft\r\nessiqowb\r\ny" +
            "mohhvfu\r\nkzjynqhe\r\nooxnssfp\r\nhpnozozp\r\nkdxkokxe\r\nrwredkrn\r\nznmrmswj\r\nsvtkdsuu\r\ni" +
            "bjqwhwi\r\nmknydjrv\r\nopchsgmr\r\ntbyvuatt\r\nigevmbpk\r\nexpjknbc\r\nkzboboox\r\nusoxsikr\r\nf" +
            "izzvucq\r\nrvjomwnd\r\nsgfcwqdl\r\nocacgxpj\r\nmropbfvf\r\nxexycbuo\r\nqngxnnud\r\nitmenmlm\r\nd" +
            "yaqaifs\r\njwgtqejq\r\neyeaavrj\r\nvwyjauhk\r\nhqajvjkh\r\nddvhuacy\r\ngjgrgtll\r\nmgawuelx\r\nl" +
            "mdgzggf\r\npbtgkvxc\r\nsvwklnwu\r\nkvtsovnm\r\noybxcuqk\r\nufwkjtlj\r\nxkrgfyad\r\nkdgdjzqp\r\ni" +
            "qdgesbu\r\nmxpocjsl\r\nrmwvihpw\r\nbpbftisr\r\nkgtgxxqw\r\nypwjafxu\r\nhihxitsz\r\nlnntwahr\r\ns" +
            "secoqkz\r\nynktphtd\r\nskwfmfpw\r\nbihrglvz\r\nxzkjkgjm\r\ncuozrxqe\r\nqmcfrurm\r\ntphowbli\r\nz" +
            "vzwyhrv\r\nvzlfbuor\r\nvblsrrba\r\nlakiynlc\r\nafomthrw\r\nrbgtoyfq\r\nahkqljen\r\ngamoerak\r\nw" +
            "umjelwi\r\nvqimktjy\r\nlevvfcsq\r\neuwrqnjp\r\nfapllntx\r\nvyzlxslf\r\nrwhcbrvz\r\ntxpficpp\r\nm" +
            "bwpimjr\r\nzohppwog\r\nzdrsdecc\r\nuaxqlvsh\r\nykerbsdc\r\naecktaff\r\nwrtdufue\r\ngykyrwcv\r\ns" +
            "esrvnsp\r\nhmopnqyy\r\ntfuulvec\r\njdokvsfw\r\njwkhzpaf\r\nmjvzffxn\r\npctkfrtb\r\nwfiwcoxg\r\nq" +
            "odzwvbg\r\nbrcaggnu\r\njjjrrtiu\r\nktkobacy\r\nnahinlmj\r\nnszbvcmi\r\nnfvbldhe\r\ntjweqfgt\r\nc" +
            "rabmuxk\r\naffxwlpf\r\nmpominpv\r\nyufjtaaa\r\nhzzhmsyx\r\nplwdkozp\r\nozbgwwvd\r\npplerubj\r\nw" +
            "zumeuqo\r\nksynbxaf\r\nyxeircsj\r\ngaqlykne\r\nirsltmrz\r\njifivecj\r\nvhwsstkq\r\nmjiiiuab\r\nn" +
            "kimvhvg\r\nmemuhxrh\r\ntjvbzypn\r\nglebcdpn\r\nzrmcpufo\r\nimxlujrn\r\nacftqbcf\r\nsymmrhuj\r\nl" +
            "qkrybxd\r\njsyxqzqt\r\nxbqjvjxl\r\nqwqsvysm\r\nddjypobl\r\nrwxyfjby\r\nwpoiklyi\r\neiftosiu\r\nc" +
            "abwkqhx\r\nyxtbhlxo\r\nheismnzr\r\nyaduhfgm\r\nnghplvvs\r\nlwukrqdx\r\nifjqghtk\r\nqclffqxm\r\nc" +
            "uszvrgk\r\nocshztws\r\nhipeodcu\r\nqnbgnllz\r\nqsuogdmr\r\neusogkvt\r\nrddealkr\r\nfjrrvsco\r\nn" +
            "ugopflj\r\nbhgbdkxs\r\nfthcqpao\r\ntkdvyegv\r\ntbvpgueq\r\nahfagxlm\r\ncipkqfxj\r\nvqqcipuc\r\nm" +
            "ugdchdl\r\nwwjpnife\r\npurpypnv\r\ncqzunigd\r\nnlnvjhbd\r\nhhiqrzod\r\nfwjhmdij\r\nwkpvakif\r\nb" +
            "jrytvwo\r\nuosbgqjb\r\nbdmfzjcy\r\ndxlqldzl\r\nakqbtwvs\r\nwbxschlg\r\nmrzksrhs\r\njmvueuih\r\ne" +
            "bxpjnhp\r\nllsogwyw\r\npeyzimia\r\nmufdkyny\r\ndlvxntre\r\ndyfyazrx\r\naarkcrwe\r\nqqacegoh\r\nr" +
            "biqykai\r\ntbnkymsk\r\nebtsieby\r\nuhyjeeba\r\nahpywtnx\r\ngyvacpuf\r\nfrcyslud\r\nmwwnxofu\r\nj" +
            "zyabbkj\r\ncctdoztv\r\njztmavpd\r\nsacgyoii\r\ngnqiydic\r\nggdrerzq\r\nlduphshn\r\nhctmpgih\r\nk" +
            "qabzyjt\r\nppkztsay\r\npnusnowm\r\nulyvxfkp\r\nvmlapyyt\r\nzifxarmp\r\nvnpzxhjb\r\nraewumao\r\nw" +
            "ejyiymi\r\ngjbdfjzy\r\nbxhlwziy\r\nrsqlgthf\r\nxtkaltqu\r\nsmiarmpw\r\nxdypfzem\r\nyleuggnb\r\nw" +
            "gphfsve\r\nxgqmyqhq\r\niyfrymtc\r\nbwhjkhfl\r\naftctjug\r\nseibsuof\r\nngcdnmxw\r\nltxyudxa\r\nx" +
            "pwqkgdl\r\nhagwixkv\r\nlhtlmxqw\r\ndcineqxs\r\nnzdrjynu\r\nvmytcguy\r\nymsuzmox\r\nlkzvgcgh\r\nd" +
            "fjgzjdn\r\nrvmgejgk\r\ndcxdrgpz\r\nbhjsceuv\r\nnhpllxmo\r\ngkotvtsu\r\nuubvdkjg\r\nzjnerxhq\r\nb" +
            "utazmez\r\nszzvqyzs\r\nfpchqsei\r\nxfsvriyr\r\nvxodutyh\r\nzsilhmba\r\nrvacqpwj\r\nhjewdrtx\r\nb" +
            "ylcpgfs\r\nqtntvgfq\r\nioqldhye\r\nwlrbwapp\r\nnlptloss\r\nznnybfvl\r\neinvacbu\r\nkyziepsr\r\nf" +
            "thuwmlv\r\npmkbhvdn\r\nxuxngboe\r\ntpoinkzc\r\nzwbnhlwp\r\nusuusbin\r\njiulcmsq\r\nelcusgvu\r\nf" +
            "rclhdyo\r\npvmirlch\r\njvrjfxmb\r\nsxmtcrsw\r\nccfkmgmw\r\nmdnibgld\r\nidmojsza\r\nhsjvyoua\r\ns" +
            "mhwbpax\r\npgcozahq\r\ndstdnwle\r\naiikfrxt\r\nkmbnsppa\r\nwsxcbwze\r\nhqyunies\r\nmfrxeqyw\r\nz" +
            "ikpwtqz\r\nzckxtclz")]
        public string Setting_PuzzleInput {
            get {
                return ((string)(this["Setting_PuzzleInput"]));
            }
            set {
                this["Setting_PuzzleInput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("eedadn\r\ndrvtee\r\neandsr\r\nraavrd\r\natevrs\r\ntsrnev\r\nsdttsa\r\nrasrtv\r\nnssdts\r\nntnada\r\ns" +
            "vetve\r\ntesnvt\r\nvntsnd\r\nvrdear\r\ndvrsen\r\nenarar")]
        public string Setting_PuzzleInput_Sample {
            get {
                return ((string)(this["Setting_PuzzleInput_Sample"]));
            }
            set {
                this["Setting_PuzzleInput_Sample"] = value;
            }
        }
    }
}
